volumes:
  docker:
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - docker:/data/db

  yobulk:
    image: yobulk/yobulk
    ports:
      - 8000:3000
    environment:
      MONGODB_URI: mongodb://database:27017/yobulk
    depends_on:
      - database
